### ISSUE TITLE
Mode map hides magit-cherry

### ISSUE THREAD

**Issue by llvilanova** [magit/magit-stgit#6]
The StGit popup is currently bound to 'Y', which is originally mapped to 'magit-cherry'.

Any opinions from the main developers on what is an acceptable free binding for the popup?

**Comment by tarsius** [comment]
I can't really think of a good one that isn't taken yet. You might have to use a non-alphabetic key.

**Comment by tarsius** [comment]
On the other hand, doesn't stgit provide features which one would use *instead* of `git cherry`? In that case shadowing `magit-cherry` would be okay, I guess.
